export const SENSOR_NAMES = {
  1: "UV Index",
  2: "pH",
  3: "CO2",
  4: "Barometer",
  5: "IR Temp",
  6: "Humidity",
  7: "GPS",
  8: "GPS Latitude",
  9: "GPS Longitude",
  10: "GPS Speed",
  11: "GPS Course",
  13: "Ext. Temperature",
  14: "Colorimeter",
  15: "Color R",
  16: "Color G",
  17: "Color B",
  20: "Light",
  21: "Sound Level",
  22: "Pulse",
  23: "Heart Rate",
  24: "Pulse Waveform",
  25: "Distance",
  26: "Air Pressure",
  27: "Voltage",
  28: "Current",
  29: "Humidity Analog",
  30: "Amb. Temperature",
  31: "Turbidity",
  32: "External Input 1",
  33: "Microphone",
  34: "Low Voltage",
  36: "Acceleration X",
  37: "Acceleration Y",
  38: "Acceleration Z",
  39: "External Input 2",
  40: "Dissolved O₂",
  41: "Conductivity",
  42: "Thermocouple",
  47: "Barometer KPa",
  48: "Ion",
  49: "Mini Voltage",
  50: "Mini Current",
};
